-- Run this in Supabase SQL Editor

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references categories(id) on delete cascade,
  name text not null,
  description text,
  price text,
  image_path text,
  active boolean not null default true
);

create table if not exists qr_scans (
  id bigint generated by default as identity primary key,
  scanned_at text not null,
  scanned_date text not null
);

create index if not exists idx_products_category on products(category_id);
create index if not exists idx_qr_scans_date on qr_scans(scanned_date);
